package com.bankfusion.corebanking.entity;


import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Date;
import java.util.List;

@Entity
@Table(name = "CUSTOMER",schema = "BANKFUSION")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Customer {
    @Id
    private String customerID;
    private String customerName;
    private Date customerDOB;


    @Lob
    @Column(columnDefinition = "TEXT")
    private String customerAddress;

    private String mobileNumber;

    @OneToMany(
            mappedBy = "customer",
            cascade = CascadeType.ALL
    )
    private List<Account> accountList;

    private Character gender;

    private Boolean isAutoGenerated;

    @Version
    private Long version;
}
