package com.fincorex.corebanking.service.impl;

import com.fincorex.corebanking.constants.ApiConstants;
import com.fincorex.corebanking.dto.CustomerRqDTO;
import com.fincorex.corebanking.dto.CustomerRsDTO;
import com.fincorex.corebanking.entity.Customer;
import com.fincorex.corebanking.exception.BadRequestException;
import com.fincorex.corebanking.exception.CustomerNotFoundException;
import com.fincorex.corebanking.repository.CustomerRepo;
import com.fincorex.corebanking.service.CustomerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class CustomerServiceImpl implements CustomerService {
    @Autowired
    private CustomerRepo customerRepo;

    @Override
    @Transactional(rollbackFor = {Exception.class})
    public synchronized CustomerRsDTO createCustomer(CustomerRqDTO customerRqDTO) throws BadRequestException {
        Boolean isAutogenerated = (customerRqDTO.getCustomerID() == null || customerRqDTO.getCustomerID().equals("")) ? Boolean.TRUE : Boolean.FALSE;
        String customerID = customerRqDTO.getCustomerID();
        if(isAutogenerated)
            customerID = generateCustomerID();
        if(customerRepo.findById(customerID).isPresent())
            throw new BadRequestException("Customer ID Already Exist");
        Customer customer = Customer.builder().customerID(customerID)
                .customerName(customerRqDTO.getCustomerName())
                .customerAddress(customerRqDTO.getCustomerAddress())
                .customerDOB(customerRqDTO.getCustomerDOB())
                .customerEmail(customerRqDTO.getCustomerEmail())
                .mobileNumber(customerRqDTO.getMobileNumber())
                .gender(customerRqDTO.getGender())
                .isAutoGenerated(isAutogenerated)
                .build();
        return buildCustomerRsDTO(customerRepo.save(customer));
    }

    @Override
    public CustomerRsDTO fetchCustomerByID(String customerID) throws CustomerNotFoundException {
        Optional<Customer> customer = customerRepo.findById(customerID);
        if(customer.isEmpty())
            throw new CustomerNotFoundException("Customer Not Found");
        return buildCustomerRsDTO(customer.get());
    }

    @Override
    public List<CustomerRsDTO> fetchAllCustomers() {
        List<Customer> customers = customerRepo.findAll();
        return customers.stream().map(this::buildCustomerRsDTO).collect(Collectors.toList());
    }

    @Override
    @Transactional(rollbackFor = {Exception.class})
    public CustomerRsDTO updateCustomerDetails(CustomerRqDTO customerRqDTO) throws CustomerNotFoundException {
        Optional<Customer> customerOptional = customerRepo.findById(customerRqDTO.getCustomerID());
        if(customerOptional.isEmpty())
            throw new CustomerNotFoundException("Customer Not Found");
        Customer customer = customerOptional.get();
        customer.setCustomerName(customerRqDTO.getCustomerName());
        customer.setCustomerAddress(customerRqDTO.getCustomerAddress());
        customer.setGender(customerRqDTO.getGender());
        customer.setCustomerDOB(customerRqDTO.getCustomerDOB());
        customer.setCustomerEmail(customerRqDTO.getCustomerEmail());
        customer.setMobileNumber(customerRqDTO.getMobileNumber());
        return buildCustomerRsDTO(customerRepo.save(customer));
    }

    public String generateCustomerID(){
        long count = customerRepo.countByIsAutoGenerated(Boolean.TRUE);
        return ApiConstants.CUSTID_PREFIX+(count+1);
    }

    public CustomerRsDTO buildCustomerRsDTO(Customer customer){
        return CustomerRsDTO.builder().customerID(customer.getCustomerID())
                .customerName(customer.getCustomerName())
                .customerAddress(customer.getCustomerAddress())
                .customerEmail(customer.getCustomerEmail())
                .customerDOB(customer.getCustomerDOB())
                .mobileNumber(customer.getMobileNumber())
                .gender(customer.getGender())
                .isAutoGenerated(customer.getIsAutoGenerated())
                .build();
    }
}
