package com.bankfusion.corebanking.repository;


import com.bankfusion.corebanking.entity.Customer;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

public interface CustomerRepo extends JpaRepository<Customer,String> {
    List<Customer> findAllByIsAutoGenerated(Boolean isAutoGenerated);
}
