package com.fincorex.corebanking.repository;


import com.fincorex.corebanking.entity.Customer;
import org.springframework.data.jpa.repository.JpaRepository;

public interface CustomerRepo extends JpaRepository<Customer,String> {
    long countByIsAutoGenerated(Boolean aTrue);
}
