package com.bankfusion.corebanking.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class CustomerRsDTO {
    private String customerID;
    private String customerName;
    private Date customerDOB;
    private String customerAddress;
    private String mobileNumber;
    private Character gender;
    private Boolean isAutoGenerated;
}
